name: shopping
description: A shopping experience.

version: 0.1.0+22070008
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.4

  single_async_widget: ^1.0.0
  shared_preferences: ^2.0.15

  http: ^0.13.4
  json_annotation: ^4.5.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1

  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  firebase_dynamic_links: ^4.2.4
  firebase_analytics: ^9.1.8
  firebase_remote_config: ^2.0.7
  firebase_crashlytics: ^2.8.0
  firebase_performance: ^0.8.0+12

  firebase_auth: ^3.3.18
  google_sign_in: ^5.3.2
  sign_in_with_apple: ^4.0.0
  flutter_facebook_auth: ^4.3.4
  flutter_signin_button: ^2.0.0

  permission_handler: ^9.2.0
  url_launcher: ^6.1.2
  share: ^2.0.4

  flutter_html: ^3.0.0-alpha.3
  path_provider: ^2.0.10
  webview_flutter: ^3.0.4
  freezed_annotation: ^2.0.3
  equatable: ^2.0.3

  riverpod: ^1.0.0
  flutter_riverpod: ^1.0.0

  logging: ^1.0.2
  logging_manager_flutter: ^2.2.1

  magnific_ui: ^0.4.0
  app_boot: ^0.3.0
  onesignal_flutter: ^3.3.0
  magnific_core: ^0.3.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.0

  go_router: ^3.1.0

  # Storage
  drift: ^1.1.1
  sqlite3_flutter_libs: ^0.5.2
  sqlite3: ^1.5.1

  path: ^1.8.0
  package_info_plus: ^1.4.2

  crypto: ^3.0.2
  system_info2: ^2.0.4
  fluentui_system_icons: ^1.1.174
  badges: ^2.0.3
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  flutter_lints: ^2.0.1
  drift_dev: ^1.1.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  # for l10n synthetic deps generation
  flutter_gen_runner: ^4.1.6
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/brand/

